### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/renderscript/RenderScript;

### ISSUE THREAD

**Issue by cikichen** [kongzue/DialogX#102]
```
W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/renderscript/RenderScript;
        at com.kongzue.dialogx.util.views.BlurView$2.run(BlurView.java:486)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.renderscript.RenderScript" on path: DexPathList[[zip file "/data/app/com.-s5qnF0hKxSpO9vDd0XofQg==/base.apk"],nativeLibraryDirectories=[/data/app/com.s5qnF0hKxSpO9vDd0XofQg==/lib/arm64, /data/app/com.s5qnF0hKxSpO9vDd0XofQg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 1 more
```

**Comment by kongzue** [comment]
请忽略此提示，并无实际影响。
RenderScript 是 Google 提供的快速计算类，DialogX 使用其实现在 iOS 主题下的模糊效果，如果你需要使用，请按照 [wiki 文档](https://github.com/kongzue/DialogX/wiki) 中的说明引入此库，请注意，引入此库将带来额外的软件包体积增加。
若你不需要使用，请无视此警告，并不会有任何影响，当你编译为 release 版本是请关闭 DialogX.DEBUGMODE，将不再显示此提示，方法为：
```
DialogX.DEBUGMODE = false;
```
