### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#117]
已经初始化了，但还是偶然会出现这个问题。

应该是退到后台，再次开启后，你的内部弱引用被释放了。

```
09-19 23:50:16.022  7172  7172 E >>>[79] : DialogX 未初始化。
09-19 23:50:16.022  7172  7172 E >>>[79] : 请检查是否在启动对话框前进行初始化操作，使用以下代码进行初始化：
09-19 23:50:16.022  7172  7172 E >>>[79] : DialogX.init(context);
09-19 23:50:16.022  7172  7172 E >>>[79] : 
09-19 23:50:16.022  7172  7172 E >>>[79] : 另外建议您前往查看 DialogX 的文档进行使用：https://github.com/kongzue/DialogX
09-19 23:50:16.055  7172  7172 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
09-19 23:50:16.056  7172  7172 E DEBUG   : Process Name: com.x'
09-19 23:50:16.056  7172  7172 E DEBUG   : Thread Name: 'main'
09-19 23:50:16.056  7172  7172 E DEBUG   : Back traces starts.
09-19 23:50:16.056  7172  7172 E DEBUG   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at android.view.LayoutInflater.from(LayoutInflater.java:299)
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at d.s.a.f.b.b(Unknown Source:4)
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at d.s.a.d.o$a.run(:1)
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at android.os.Handler.handleCallback(Handler.java:883)
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-19 23:50:16.057  7172  7172 E DEBUG   : 	at android.os.Looper.loop(Looper.java:230)
09-19 23:50:16.058  7172  7172 E DEBUG   : 	at android.app.ActivityThread.main(ActivityThread.java:7851)
09-19 23:50:16.058  7172  7172 E DEBUG   : 	at java.lang.reflect.Method.invoke(Native Method)
09-19 23:50:16.058  7172  7172 E DEBUG   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
09-19 23:50:16.058  7172  7172 E DEBUG   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-19 23:50:16.058  7172  7172 E DEBUG   : Back traces ends.
09-19 23:50:16.058  7172  7172 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
```

**Comment by kongzue** [comment]
请在回收并重新切换至前台的情况下，重新初始化DialogX

**Comment by kongzue** [comment]
Tips，Application并非弱引用，应该是Application释放后，内部的ActivityLifecycleCallbacks被清空，导致DialogX无法拿到堆栈顶端的Activity导致了此问题，建议在 Activity 的 onResume 保持下DialogX 的初始化，我也会继续寻找此问题的处理办法

**Comment by kongzue** [comment]
请尝试版本 0.0.43.beta16。
若后续再遇到此问题请回复我。
