### ISSUE TITLE
WaitDialog崩溃

### ISSUE THREAD

**Issue by kagurasansan** [kongzue/DialogX#126]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.init(WaitDialog.java:305)
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:270)
        at com.kongzue.dialogx.dialogs.WaitDialog$1.run(WaitDialog.java:209)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by kongzue** [comment]
请确认您是否使用最新的测试版本0.0.43.beta12。
在早前已对这里进行修改，当前最新版本代码 [WaitDialog.java:305](https://github.com/kongzue/DialogX/blob/514886755e0d55e92af825bd1f9e129812174f3e/DialogX/src/main/java/com/kongzue/dialogx/dialogs/WaitDialog.java#L305) 已无类似逻辑。

**Comment by kagurasansan** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.init(WaitDialog.java:312)
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:277)
        at com.kongzue.dialogx.dialogs.WaitDialog$2.run(WaitDialog.java:233)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)  升级到最新版本还是崩溃

**Comment by kongzue** [comment]
依然无法复现此问题。
能提供下你启动 WaitDialog 的代码么？另外此问题是必现的么？以及您的设备、系统版本

**Comment by kagurasansan** [comment]
每次app首次冷启动从登录进入首页后就会崩溃,之后不复现，杀端后再从登录进首页还会崩溃,dialogx在application oncreate中已经初始化，
手机型号：华为荣耀HRY-AL00a android10 EMUI: 10.0.0
public void showDialog(String title) {
         WaitDialog.show(this,title)
                .setOnBackPressedListener(new OnBackPressedListener() {
            @Override
            public boolean onBackPressed() {
                WaitDialog.dismiss();
                return false;
            }
        }).setBackgroundColorRes(R.color.color_99000);
    }

  public void dismissDialog() {
        WaitDialog.dismiss();
    }

**Comment by kongzue** [comment]
你再试一下最新的beta版看还有没有类似的问题

________________________________
发件人: kagurasansan ***@***.***>
发送时间: Saturday, October 2, 2021 5:44:30 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] WaitDialog崩溃 (#126)


每次app首次冷启动从登录进入首页后就会崩溃,之后不复现，杀端后再从登录进首页还会崩溃,dialogx在application oncreate中已经初始化，
手机型号：华为荣耀HRY-AL00a android10 EMUI: 10.0.0
public void showDialog(String title) {
WaitDialog.show(this,title)
.setOnBackPressedListener(new OnBackPressedListener() {
@OverRide<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOverRide&data=04%7C01%7C%7C1679d26d34714e163f3d08d985893bbe%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687646747996965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F4%2FXpmeJLOZevEx7QzUdXW8sMCbXwl5Uanc%2Fio5AyoY%3D&reserved=0>
public boolean onBackPressed() {
WaitDialog.dismiss();
return false;
}
}).setBackgroundColorRes(R.color.color_99000);
}

public void dismissDialog() {
WaitDialog.dismiss();
}

―

**Comment by kagurasansan** [comment]
我试了一下还是崩溃

**Comment by kongzue** [comment]
暂时不清楚华为的系统做了什么处理，未能在Android12 Pixel5上复现此问题
________________________________
发件人: kagurasansan ***@***.***>
发送时间: Saturday, October 2, 2021 5:52:07 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] WaitDialog崩溃 (#126)


我试了一下还是崩溃

―

**Comment by kongzue** [comment]
![Uploading image.png…]()
