### ISSUE TITLE
操作几次之后，会发生java.util.ConcurrentModificationException异常闪退

### ISSUE THREAD

**Issue by chenhao1041661180** [kongzue/DialogX#140]
Process: com.kongzue.dialogxdemo, PID: 30145
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.kongzue.dialogx.dialogs.PopTip.waitForDismiss(PopTip.java:632)
        at com.kongzue.dialogx.dialogs.PopTip.access$1800(PopTip.java:53)
        at com.kongzue.dialogx.dialogs.PopTip$DialogImpl$7$1.run(PopTip.java:609)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)

**Comment by kongzue** [comment]
麻烦问下是在异步线程执行的PopTip么？
此问题会在下一个版本得到修复。

**Comment by chenhao1041661180** [comment]
使用的是当前这个项目操作的

**Comment by kongzue** [comment]
是使用Demo操作的么？

**Comment by kongzue** [comment]
很抱歉，经过测试，未能复现您所描述的问题。测试环境为 Pixel5(Android 12)，频繁启动PopTip

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，若有疑问请继续回复。
