### ISSUE TITLE
布局强制转换问题

### ISSUE THREAD

**Issue by zhanghuibiao** [kongzue/DialogX#153]
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.kongzue.dialogx.util.views.MaxLinearLayout
        at com.kongzue.dialogx.dialogs.PopMenu$DialogImpl.<init>(PopMenu.java:234)
        at com.kongzue.dialogx.dialogs.PopMenu.show(PopMenu.java:187)
        at com.kongzue.dialogx.dialogs.PopMenu.show(PopMenu.java:135)
        at com.kongzue.dialogxdemo.activity.MainActivity$7.onClick(MainActivity.java:329)

**Comment by kongzue** [comment]
请更新 0.0.44.beta6 测试版已修复此问题。
