### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference

### ISSUE THREAD

**Issue by wosika** [kongzue/DialogX#157]
首先非常感谢作者发布的这么好的仓库，使用体验非常棒，也从代码学习到很多~
目前出现一个问题，特来反馈一下。
使用版本：0.0.44.beta8

初始化代码：

        DialogX.init(this)
        DialogX.globalStyle = IOSStyle()
        DialogX.enterAnimDuration = 100
        DialogX.exitAnimDuration = 100
        
错误产生原因：
当调用
``CustomDialog.dismiss()``
马上接着调用
``WaitDialog.setMessage(text).setCancelable(true).show() ``
导致崩溃产生。
目前我自己尝试的解决方案是
``CustomDialog.dismiss()`` 之后 延迟300毫秒再调用``WaitDialog.setMessage(text).setCancelable(true).show() ``则崩溃不产生。
好像是与dialog显示消失的动画有关系？

 
 具体错误：
 ``` 
   java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4355)
        at android.view.View.draw(View.java:22521)
        at com.android.internal.policy.DecorView.draw(DecorView.java:955)
        at android.view.View.updateDisplayListIfDirty(View.java:21394)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:571)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4237)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3951)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3219)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2029)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8620)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1073)
        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
        at android.view.Choreographer.doFrame(Choreographer.java:818)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1058)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:8158)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:959)

**Comment by kongzue** [comment]
收到，此问题已列入待验证

**Comment by kongzue** [comment]
此问题已验证，将在下一个版本修复

**Comment by kongzue** [comment]
请更新至 0.0.44.beta9 版本已修复此问题：https://github.com/kongzue/DialogX/releases
