### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference

### ISSUE THREAD

**Issue by pressureKai** [kongzue/DialogX#173]
初始化代码
 DialogX.init(application)
 DialogX.implIMPLMode= DialogX.IMPL_MODE.FLOATING_ACTIVITY

版本
 def dialogx_version = "0.0.44.beta14"
 implementation "com.github.kongzue.DialogX:DialogX:${dialogx_version}"

当调用 CustomDialog.dismiss 出现报错

2022-02-21 15:04:08.772 21521-21521/  E/DEBUG: java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
2022-02-21 15:04:08.772 21521-21521/  E/DEBUG:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
2022-02-21 15:04:08.772 21521-21521/  E/DEBUG:     at android.view.View.draw(View.java:22476)
2022-02-21 15:04:08.772 21521-21521/  E/DEBUG:     at com.android.internal.policy.DecorView.draw(DecorView.java:826)
2022-02-21 15:04:08.773 21521-21521/  E/DEBUG:     at android.view.View.updateDisplayListIfDirty(View.java:21341)
2022-02-21 15:04:08.773 21521-21521/  E/DEBUG:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
2022-02-21 15:04:08.773 21521-21521/  E/DEBUG:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
2022-02-21 15:04:08.773 21521-21521/  E/DEBUG:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
2022-02-21 15:04:08.773 21521-21521/  E/DEBUG:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:4239)
2022-02-21 15:04:08.774 21521-21521/  E/DEBUG:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3953)
2022-02-21 15:04:08.774 21521-21521/  E/DEBUG:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3224)
2022-02-21 15:04:08.774 21521-21521/  E/DEBUG:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2064)
2022-02-21 15:04:08.774 21521-21521/  E/DEBUG:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8395)
2022-02-21 15:04:08.774 21521-21521/  E/DEBUG:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
2022-02-21 15:04:08.775 21521-21521/  E/DEBUG:     at android.view.Choreographer.doCallbacks(Choreographer.java:880)
2022-02-21 15:04:08.775 21521-21521/  E/DEBUG:     at android.view.Choreographer.doFrame(Choreographer.java:813)
2022-02-21 15:04:08.775 21521-21521/  E/DEBUG:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
2022-02-21 15:04:08.775 21521-21521/  E/DEBUG:     at android.os.Handler.handleCallback(Handler.java:938)
2022-02-21 15:04:08.775 21521-21521/  E/DEBUG:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-02-21 15:04:08.776 21521-21521/  E/DEBUG:     at android.os.Looper.loop(Looper.java:236)
2022-02-21 15:04:08.776 21521-21521/  E/DEBUG:     at android.app.ActivityThread.main(ActivityThread.java:7879)
2022-02-21 15:04:08.776 21521-21521/  E/DEBUG:     at java.lang.reflect.Method.invoke(Native Method)
2022-02-21 15:04:08.777 21521-21521/  E/DEBUG:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2022-02-21 15:04:08.777 21521-21521/  E/DEBUG:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

bug备注，特定机型报错（另外一个荣耀平板运行正常）
<img width="909" alt="image" src="https://user-images.githubusercontent.com/28721119/154906016-a7270ec1-69bd-4fab-a801-639070edde08.png">

DialogX.implIMPLMode= DialogX.IMPL_MODE.FLOATING_ACTIVITY 初始化时使用这句代码会报错

在AndroidManifest中注册如下:

 <activity android:name="com.kongzue.dialogx.util.DialogXFloatingWindowActivity"
            android:screenOrientation="portrait"
            android:theme="@style/OnePixelActivity"/>

DialogXFloatingWindowActivity 应用的主题如下：

<style name="OnePixelActivity" parent="Theme.AppCompat.Light.NoActionBar">//无标题
        <item name="android:windowIsTranslucent">true</item>//透明
        <item name="android:background">@color/transparent</item>
        <item name="android:windowBackground">@color/transparent</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>

**Comment by kongzue** [comment]
请注意，implIMPLMode尚处于实验性质，不建议在生产环境使用。根据堆栈日志无法确定原因，可能是View内的mViewFlags存在问题，并非DialogX报错，暂时无法处理。

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
