### ISSUE TITLE
【BUG反馈】MessageDialog crash

### ISSUE THREAD

**Issue by KunMinX** [kongzue/DialogX#213]
android 12 miui，根据 wiki 测试 `MessageDialog.show("标题", "正文内容", "确定");` crash

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
```

**Comment by kongzue** [comment]
请给出具体的错误堆栈信息

**Comment by KunMinX** [comment]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
   at com.kongzue.dialogx.interfaces.BaseDialog.show(BaseDialog.java:152)
   at com.kongzue.dialogx.dialogs.MessageDialog.show(MessageDialog.java:214)
   at com.kongzue.dialogx.dialogs.MessageDialog.show(MessageDialog.java:126)
   at com.xinyue.zhuanpan.ui.page.MainActivity.onCreate(MainActivity.java:58)
   at android.app.Activity.performCreate(Activity.java:8238)
   at android.app.Activity.performCreate(Activity.java:8206)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3712)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3906) 
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259) 
   at android.os.Handler.dispatchMessage(Handler.java:106) 
   at android.os.Looper.loopOnce(Looper.java:210) 
   at android.os.Looper.loop(Looper.java:299) 
   at android.app.ActivityThread.main(ActivityThread.java:8105) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
```

**Comment by kongzue** [comment]
需要确认下是否在执行show指令之前正确的初始化：
```
DialogX.init(context);
```
也有可能在程序刚启动时未能正确的获取到顶层 Activity（topActivity），此问题会在下一版本尝试性修复

**Comment by kongzue** [comment]
请尝试新版本0.0.45.beta21
[0.0.45.beta21测试版更新](https://github.com/kongzue/DialogX/releases/tag/0.0.45.beta21)

**Comment by KunMinX** [comment]
如 application 添加 DialogX.init(context)，可，
故建议于 crash 处提供 init 提示，或 MessageDialog wiki 中提供说明，因不是每种 dialogX 之正常使用都需 init，
新版已确认无 crash。
