### ISSUE TITLE
手机显示放大后WaitDialog崩溃

### ISSUE THREAD

**Issue by doiten** [kongzue/DialogX#241]
用的DialogXIOSStyle，在手机显示放大后，loading动画导致崩溃；
 java.lang.IllegalArgumentException: x must be >= 0
        at android.graphics.Bitmap.checkXYSign(Bitmap.java:547)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:995)
        at com.kongzue.dialogx.style.views.ProgressView.getLoadingBitmap(ProgressView.java:211)
        at com.kongzue.dialogx.style.views.ProgressView.onDraw(ProgressView.java:188)
        at android.view.View.draw(View.java:21999)
        at android.view.View.updateDisplayListIfDirty(View.java:20859)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.View.draw(View.java:21726)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
        at android.view.View.draw(View.java:22002)
        at android.view.View.updateDisplayListIfDirty(View.java:20859)
        at android.view.View.draw(View.java:21726)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
        at android.view.View.draw(View.java:22002)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1173)
        at android.view.View.updateDisplayListIfDirty(View.java:20859)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

还有bottommenu在列表数据很多的情况setSelection()导致卡顿。

**Comment by kongzue** [comment]
未能发现合理的触发异常的原因，但在代码 [ProgressView.java:211](https://github.com/kongzue/DialogX/blob/bd482922069b7fb990ec1b4634978cc207f34774/DialogXIOSStyle/src/main/java/com/kongzue/dialogx/style/views/ProgressView.java#L211) 处已经做了加固处理：
```java
private Bitmap getLoadingBitmap() {
    Bitmap origin = BitmapFactory.decodeResource(getResources(), isLightMode ? R.mipmap.img_progress_ios_light : R.mipmap.img_progress_ios_dark);
    Matrix matrix = new Matrix();
    matrix.setRotate(45 * ((int) currentRotateDegrees));
    Bitmap rotatedBitmap = Bitmap.createBitmap(origin, 0, 0, origin.getWidth(), origin.getHeight(), matrix, false);
    int x = rotatedBitmap.getWidth() / 2 - origin.getWidth() / 2;
    int y = rotatedBitmap.getHeight() / 2 - origin.getHeight() / 2;
    if (x < 0) x = 0;
    if (y < 0) y = 0;
    return Bitmap.createBitmap(rotatedBitmap, x, y, origin.getWidth(), origin.getHeight(), null, false);
}
```
会在下一个版本生效，经过我们测试也未能复现 x、y 值为负数的情况，尚不清楚为何会导致此问题发生。
另外 BottomMenu 不适用于大量数据的选择，如果有大量数据选择的需求，更建议使用自定义布局加 RecycleView 进行实现，Demo中有样例。

**Comment by kongzue** [comment]
此问题已经在最新的更新中修复：https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta14

**Comment by doiten** [comment]
修复后的还是有错
` java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
        at android.graphics.Bitmap.createBitmap(Bitmap.java:998)
        at com.kongzue.dialogx.style.views.ProgressView.getLoadingBitmap(ProgressView.java:210)
        at com.kongzue.dialogx.style.views.ProgressView.onDraw(ProgressView.java:183)
        at android.view.View.draw(View.java:21999)
        at android.view.View.updateDisplayListIfDirty(View.java:20859)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.View.draw(View.java:21726)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
        at android.view.View.draw(View.java:22002)
        at android.view.View.updateDisplayListIfDirty(View.java:20859)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
        at android.view.View.updateDisplayListIfDirty(View.java:20817)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)`

**Comment by kongzue** [comment]
很奇怪，我这边在Google Pixel5(Android 13)、小米12SU（Android 12）上测试均未发现任何问题，包括横竖屏切换也没用发现异常，不清楚你的设备为什么存在这些异常。

**Comment by doiten** [comment]
我这边小米11（Android 11） 也出现了这个情况

**Comment by kongzue** [comment]
我这边用小米云测平台小米11（Android 12，没能找到Android 11的测试机）进行测试未能复现此问题。
测试截图：
![d487f279 (1)](https://user-images.githubusercontent.com/10115359/189258982-419deaa4-7fbb-40eb-b189-031ceb64a483.jpg)
![d487f279 (2)](https://user-images.githubusercontent.com/10115359/189258986-75733c3c-f890-456e-8fbe-ed70135cf7bd.jpg)
![d487f279 (3)](https://user-images.githubusercontent.com/10115359/189258987-bbeb7a91-25a4-4bcf-a732-ffe8b9605118.jpg)
![d487f279](https://user-images.githubusercontent.com/10115359/189258990-23915292-268e-483e-8617-a5e113bf0652.jpg)

**Comment by kongzue** [comment]
尚不清楚原因，但会在下一个版本中进行处理：
```java
private Bitmap getLoadingBitmap() {
    Bitmap origin = BitmapFactory.decodeResource(getResources(), isLightMode ? R.mipmap.img_progress_ios_light : R.mipmap.img_progress_ios_dark);
    Matrix matrix = new Matrix();
    matrix.setRotate(45 * ((int) currentRotateDegrees));
    Bitmap rotatedBitmap = Bitmap.createBitmap(origin, 0, 0, origin.getWidth(), origin.getHeight(), matrix, false);
    int x = rotatedBitmap.getWidth() / 2 - origin.getWidth() / 2;
    int y = rotatedBitmap.getHeight() / 2 - origin.getHeight() / 2;
    int w = origin.getWidth();
    int h = origin.getHeight();
    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if (x + w > rotatedBitmap.getWidth()) w = rotatedBitmap.getWidth() - x;
    if (y + h > rotatedBitmap.getHeight()) h = rotatedBitmap.getHeight() - y;
    
    return Bitmap.createBitmap(rotatedBitmap, x, y, w, h, null, false);
}
代码已提交 Github
```

**Comment by doiten** [comment]
用你的demo确实没出现这个问题，但是在自己的APP里就会出现😢😢
另外，新增的  _OnBackPressedListener 新增当前对话框实例参数；_ 导致DialogXSample项目中相关地方出现问题

**Comment by doiten** [comment]
哈哈哈，找到原因了，我用了张高分辨率的图替换了img_progress_ios_dark这个资源
