### ISSUE TITLE
APP闪退

### ISSUE THREAD

**Issue by jackandroid2016** [kongzue/DialogX#252]
## BUG 反馈
APP闪退

### 问题描述：
app闪退，偶现
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.kongzue.dialogx.impl.DialogFragmentImpl: could not find Fragment constructor
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
                 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
                 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                 	at com.workeva.common.ui.activity.BaseActivity.onCreate(BaseActivity.java:80)
                 	at android.app.Activity.performCreate(Activity.java:7802)
                 	at android.app.Activity.performCreate(Activity.java:7791)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                 	at cn.ijiami.callm.j.ProxyInstrumentation.callActivityOnCreate(Hl:2)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437) 
                 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5307) 
                 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5215) 
                 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041) 
                 	at android.os.Handler.dispatchMessage(Handler.java:107) 
                 	at android.os.Looper.loop(Looper.java:214) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7386) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
                 Caused by: java.lang.NoSuchMethodException: com.kongzue.dialogx.impl.DialogFragmentImpl.<init> []
                 	at java.lang.Class.getConstructor0(Class.java:2332)
                 	at java.lang.Class.getConstructor(Class.java:1728)
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322) 
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                 	at com.workeva.common.ui.activity.BaseActivity.onCreate(BaseActivity.java:80) 
                 	at android.app.Activity.performCreate(Activity.java:7802) 
                 	at android.app.Activity.performCreate(Activity.java:7791) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
                 	at cn.ijiami.callm.j.ProxyInstrumentation.callActivityOnCreate(Hl:2) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437) 
                 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5307) 
                 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5215) 
                 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041) 
                 	at android.os.Handler.dispatchMessage(Handler.java:107) 
                 	at android.os.Looper.loop(Looper.java:214) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7386) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，若有疑问请继续回复。
