### ISSUE TITLE
弱引用，空指针闪退

### ISSUE THREAD

**Issue by JasonToJan** [kongzue/DialogX#255]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.init(WaitDialog.java:312)
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:277)
        at com.kongzue.dialogx.dialogs.WaitDialog$2.run(WaitDialog.java:233)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8060)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by kongzue** [comment]
未能在最新版本的代码 [WaitDialog.java:312](https://github.com/kongzue/DialogX/blob/3d58e14191b847ce7c5a9a0d0394bf6e81386a77/DialogX/src/main/java/com/kongzue/dialogx/dialogs/WaitDialog.java#L312) 找到上述错误源，请确保更新至最新版本
另外，请确保你正在使用 WaitDialog 的 Activity 非空，也可以使用 WaitDialog.show(activity, ...) 来指定要显示在哪个界面上。

**Comment by JasonToJan** [comment]
感谢大佬反馈 升级后暂未发现异常

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭了此问题，若有疑问请继续回复。
