### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Moriafly** [kongzue/DialogX#265]
DialogX 版本 0.0.47.beta13

java.lang.NullPointerException: Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference
at com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(Unknown Source:26)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8250)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by kongzue** [comment]
无法准确的定位到问题的原因，但会尝试在接下来的版本中对 boxCustom 增加判空处理。

**Comment by kongzue** [comment]
请更新至 [0.0.47.beta14](https://github.com/kongzue/DialogX/tree/0.0.47.beta14) 版本，请注意由于近期 jitpack 服务不稳定此版本建议切换至 MavenCentral 源：
![image](https://user-images.githubusercontent.com/10115359/209287207-620120eb-d506-4e26-b923-2f4e643527ca.png)

**Comment by Moriafly** [comment]
非常感谢^ω^

**Comment by kongzue** [comment]
刚刚发现此版本依然存在一个引入问题正在紧急修复预计稍晚发布一个新版本

**Comment by kongzue** [comment]
[0.0.47.beta15](https://github.com/kongzue/DialogX/releases/tag/0.0.47.beta15) 已处理无法编译的依赖问题
