### ISSUE TITLE
【BUG反馈】0.0.47版本疑似存在和软键盘冲突问题

### ISSUE THREAD

**Issue by mos1128** [kongzue/DialogX#275]
### 问题描述：
在拉起软键盘后，调用MessageDialog、InputDialog、WaitDialog和TipDialog均有此问题，其他dialog与pop操作正常（顺序交换也是）。  
测试0.0.46无此问题，0.0.48暂未测试

### 设备信息：
adv（安卓10）、逍遥模拟器（安卓7）、真机安卓13

### 是否在 Demo 中能复现此问题？
未尝试

**Comment by kongzue** [comment]
很抱歉未能理解你所描述的问题。
请具体说明问题是什么。DialogX的对话框在弹出时会将焦点转移至对话框UI，而输入法是需要将焦点保持在一个绑定的输入框对象上的（需要其windowToken），因此不支持在输入法弹起时弹出对话框并保持输入法依然处于开启状态，这会造成用户操作逻辑错误，当对话框弹出时，理应聚焦于前台的对话框UI进行操作而不是继续后边界面UI的操作。

**Comment by mos1128** [comment]
#我的测试场景是有一个EditText一个button，当我点击EditText呼出软键盘输入后（无论是否收起软键盘），点击button调用DialogX的对话框都会造成崩溃。  
报错是AbstractMethodError，但是我已经按照提示填写了混淆规则，0.0.46版本正常
```
java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:11779)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7550)
	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:107)
	at android.view.InsetsController.lambda$new$3$android-view-InsetsController(InsetsController.java:688)
	at android.view.InsetsController$$ExternalSyntheticLambda10.run(Unknown Source:2)
	at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1652)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:260)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:244)
	at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$android-view-InsetsController$InternalAnimationControlListener(InsetsController.java:415)
	at android.view.InsetsController$InternalAnimationControlListener$$ExternalSyntheticLambda0.onAnimationUpdate(Unknown Source:13)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1666)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:775)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:738)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1170)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1189)
	at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:437)
	at android.view.InsetsController.lambda$startAnimation$7$android-view-InsetsController(InsetsController.java:1635)
	at android.view.InsetsController$$ExternalSyntheticLambda3.run(Unknown Source:12)
	at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:68)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3697)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9375)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:408)
	at android.view.Choreographer.doFrame(Choreographer.java:900)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by kongzue** [comment]
根据堆栈日志没有发现DialogX相关的错误，推测是系统底层的问题，不过根据更新日志推断，可能是 [DialogX-Release 0.0.47.beta11](https://github.com/kongzue/DialogX/releases/tag/0.0.47.beta11) 这个更新间接导致的。从 0.0.47.beta11 版本起，引入了Android的新API，可以时输入法弹出时对话框的高度衔接更为流畅，但这需要将自己的 app 的 AppCompat 支持库升级到 1.3.0+ 以上版本才能生效。

请尝试将AppCompat支持库升级到 1.3.0+ 以上版本看看能否解决问题。

**Comment by mos1128** [comment]
解决，把这个忽略了。
非常感谢

**Comment by YanYanLun** [comment]
请问下这个问题具体怎么解决的 ，我也遇到了，用的最新版

**Comment by YanYanLun** [comment]
-keepclassmembers class androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback {
  *** on*(...);
}

**Comment by YanYanLun** [comment]
以上是混淆需要排除的，记录下这个问题
-keepclassmembers class androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback {
*** on*(...);
}
