### ISSUE TITLE
【BUG反馈】界面销毁后Dismiss会闪退,建议添加状态的检测,以便于网络请求回调,防止其出错

### ISSUE THREAD

**Issue by bwmgd** [kongzue/DialogX#288]
### 问题描述：
```
FATAL EXCEPTION: main
                 Process: com.boe.itc.pms, PID: 28901
                 java.lang.IllegalStateException: no event down from INITIALIZED
                 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:142)
                 	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
                 	at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$1.onDismiss(WaitDialog.java:377)
                 	at com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.onDetachedFromWindow(DialogXBaseRelativeLayout.java:270)
                 	at android.view.View.dispatchDetachedFromWindow(View.java:20547)
                 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3942)
                 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5560)
                 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5531)
                 	at android.view.ViewGroup.removeView(ViewGroup.java:5462)
                 	at com.kongzue.dialogx.interfaces.BaseDialog$6.run(BaseDialog.java:405)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:259)
                 	at android.app.ActivityThread.main(ActivityThread.java:8067)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
```

### 设备信息：
Android10

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by bwmgd** [comment]
版本0.0.48.beta14
在13版本上无此问题

**Comment by kongzue** [comment]
很抱歉，未能在Demo下复现此问题，测试代码如下：
```java
WaitDialog.show("Please Wait!");
//延迟500毫秒后关闭 activity
runDelayed(new Runnable() {
    @Override
    public void run() {
        finish();
    }
}, 500);
//延迟三秒后执行 WaitDialog.dismiss()
runDelayed(new Runnable() {
    @Override
    public void run() {
        WaitDialog.dismiss();
    }
}, 3000);
```
测试结果是没有任何异常，Activity 正常的进入 Destroy，DialogX 也没有出错。
此问题发生在 lifecycle 框架内，经过搜索发现存在此问题，但没有找到解决办法，会在下一个测试版本对所有 `lifecycle.setCurrentState(...)` 进行 `try{}catch` 处理。
暂不清楚 Google 为何会在 `lifecycle.setCurrentState(...)` 时抛出异常。

**Comment by kongzue** [comment]
分析了一下底层原因，应该是当目前状态处于销毁状态时，不可以跃升到其他状态或者重复设置销毁状态，但我认为，lifecycle 作为一个生命周期状态标注和管理组件不该将此问题上升到影响用户体验的步骤，在开发时通过 log 提醒给开发者应当是更合理的操作，个人不认可 Google 的处理方式。
目前的解决方案是，会在下一个版本对 `lifecycle.setCurrentState(...)` 进行 `try{}catch` 处理。
感谢你的反馈，祝软件永远不会出现 bug。

**Comment by kongzue** [comment]
此问题已经在最新测试版本修复，请更新至最新测试版本（Jitpack渠道）。
祝开发顺利。
