### ISSUE TITLE
【BUG反馈】非UI线程启动对话框时崩溃

### ISSUE THREAD

**Issue by vlln** [kongzue/DialogX#311]
### 问题描述：
在工作线程 (ConnectService.java:121, 工作线程由service启动) 中调用了
`PopTip.show("摄像头未找到").setRadius(40).iconError();`.

通常情况没有问题. 但是若此时屏幕中已经存在一个由button启动的PopTip:
```
btn.setOnClickListener(view -> {
    if(applicationModel.getCameraNetState() != ConnectService.NET_STATE_CONNECTED) {
        PopTip.show("需要连接").setRadius(40).iconWarning();
        return;
    }
```
则会崩溃:
```
android.util.AndroidRuntimeException: Animators may only be run on Looper threads
    at android.animation.ValueAnimator.end(ValueAnimator.java:1142)
    at com.kongzue.dialogx.dialogs.PopTip.moveUp(PopTip.java:741)
    at com.kongzue.dialogx.dialogs.PopTip.show(PopTip.java:292)
    at com.kongzue.dialogx.dialogs.PopTip.show(PopTip.java:197)
    at top.vlln.faster.wifi.ConnectService$2.onMissFound(ConnectService.java:121)
    at top.vlln.faster.ipCamera.CameraSearcher.lambda$static$0(CameraSearcher.java:40)
    at top.vlln.faster.ipCamera.-$$Lambda$CameraSearcher$nzshPE_bbUaXJP7OEIad38LlPPQ.run(Unknown Source:0)
    at java.lang.Thread.run(Thread.java:920)
```

### 设备信息：
relme RMX3161
dialogX: 0.0.47

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
正常情况, 屏幕中没有PopTip, 可以由工作线程启动
![工作线程正常发起tip](https://github.com/kongzue/DialogX/assets/43031803/5803d69c-5ade-48de-a8ff-9145400ce037)

崩溃情况, 工作线程发起tip前的状态, 若此时工作线程发起tip, 则会崩溃
![崩溃前的状态](https://github.com/kongzue/DialogX/assets/43031803/e1ca4ace-12ac-4503-ab9b-02a11e346680)

**Comment by kongzue** [comment]
收到，此问题将在下一个版本处理。
