### ISSUE TITLE
【BUG反馈】PopupMenu在DialogFragment模式下崩溃

### ISSUE THREAD

**Issue by bwmgd** [kongzue/DialogX#324]
### 问题描述：
```java
java.lang.IllegalArgumentException: width and height must be > 0
                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
                                    	at com.kongzue.dialogx.style.views.BlurRelativeLayout.drawBlurredBitmap(BlurRelativeLayout.java:445)
                                    	at com.kongzue.dialogx.style.views.BlurRelativeLayout.dispatchDraw(BlurRelativeLayout.java:386)
                                    	at android.view.View.updateDisplayListIfDirty(View.java:20362)
                                    	at android.view.View.draw(View.java:21226)
                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4399)
                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4160)
                                    	at android.view.View.draw(View.java:21497)
                                    	at android.view.View.updateDisplayListIfDirty(View.java:20371)
                                    	at android.view.View.draw(View.java:21226)
                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4399)
                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4160)
                                    	at android.view.View.updateDisplayListIfDirty(View.java:20362)
                                    	at android.view.View.draw(View.java:21226)
                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4399)
                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4160)
                                    	at android.view.View.updateDisplayListIfDirty(View.java:20362)
                                    	at android.view.View.draw(View.java:21226)
                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4399)
                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4160)
                                    	at android.view.View.draw(View.java:21497)
                                    	at com.android.internal.policy.DecorView.draw(DecorView.java:822)
                                    	at android.view.View.updateDisplayListIfDirty(View.java:20371)
                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3657)
                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3465)
                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2794)
                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1760)
                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7646)
                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                    	at android.view.Choreographer.doFrame(Choreographer.java:725)
                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                    	at android.os.Looper.loop(Looper.java:214)
                                    	at android.app.ActivityThread.main(ActivityThread.java:7650)
                                    	at java.lang.reflect.Method.invoke(Native Method)
                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### 设备信息：
Android10

### 是否在 Demo 中能复现此问题？
未尝试

**Comment by kongzue** [comment]
将在下一个测试版本修复。

**Comment by kongzue** [comment]
请更新至版本：[0.0.49.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta1)
