### ISSUE TITLE
【BUG反馈】Fatal Exception: android.renderscript.RSInvalidStateException: Calling RS with no Context active.

### ISSUE THREAD

**Issue by liuki2014** [kongzue/DialogX#327]
## BUG 反馈
请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。
Fatal Exception: android.renderscript.RSInvalidStateException: Calling RS with no Context active.
       at android.renderscript.RenderScript.validate(RenderScript.java:1246)
       at android.renderscript.BaseObj.getID(BaseObj.java:60)
       at android.renderscript.Script.setVar(Script.java:384)
       at android.renderscript.ScriptIntrinsicBlur.setRadius(ScriptIntrinsicBlur.java:101)
       at com.kongzue.dialogx.style.views.BlurLinearLayout.prepare(BlurLinearLayout.java:243)
       at com.kongzue.dialogx.style.views.BlurLinearLayout$3.onPreDraw(BlurLinearLayout.java:304)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4442)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

firebase 后台记录的崩溃日志
应该是使用MessageDialog iOS Style 触发的

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题
Android 13 Galaxy S20+ 5G
Android 13 OnePlus 8 Pro
Android 11  Moto G Pure
Android 13 Pixel 7 Pro
Android 13 Pixel 4a
Android 12 Galaxy S10

### 是否在 Demo 中能复现此问题？
是/否/未尝试
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。
后台记录的crash 没有截图

**Comment by liuki2014** [comment]
使用版本 com.github.kongzue.DialogX:DialogXIOSStyle:0.0.48

**Comment by kongzue** [comment]
猜测跟这个问题有关：
<img width="733" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/32a144ca-fe67-4e46-b5eb-11057f5c5fd2">
正在寻找解决方案

**Comment by kongzue** [comment]
相关代码修改已提交：https://github.com/kongzue/DialogX/commit/ed4904767c08ec734caaa66843db9016f6825758

**Comment by kongzue** [comment]
请更新至版本：[0.0.49.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta1)
