### ISSUE TITLE
网络检测中调用PopNotification引发

### ISSUE THREAD

**Issue by Li4526330** [kongzue/DialogX#331]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.post(java.lang.Runnable)' on a null object reference
                                                                                                    	at com.kongzue.dialogx.dialogs.PopNotification$DialogImpl.doDismiss(PopNotification.java:833)
                                                                                                    	at com.kongzue.dialogx.dialogs.PopNotification$4.run(PopNotification.java:997)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog.runOnMain(BaseDialog.java:741)
                                                                                                    	at com.kongzue.dialogx.dialogs.PopNotification.dismiss(PopNotification.java:993)
                                                                                                    	at com.kongzue.dialogx.dialogs.PopNotification.show(PopNotification.java:357)
                                                                                                    	at com.kongzue.dialogx.dialogs.PopNotification.show(PopNotification.java:238)
                                                                                                    	at com.lskj.dutyservicecall.receiver.NetworkManager.onReceive(NetworkManager.java:101)

**Comment by kongzue** [comment]
很奇怪的错误，只有两种可能性：1是在未真正显示PopNotification时执行了dismiss指令，DialogX的show指令需要等待主线程完成UI的构建和显示，但倘若UI未完成构建前进行了dismiss，亦或者是使用build方法构造了PopNotification但未进行show就执行了dismiss可能引发问题；
2是PopNotification的boxRoot在执行过程中被错误的卸载了，但要卸载boxRoot是个很极端的情况一般非正常操作也做不到，所以我倾向于可能性1的推论。
此问题会在下一个测试版本解决。

**Comment by kongzue** [comment]
请更新至版本：[0.0.49.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta1)
