### ISSUE TITLE
【BUG反馈】Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogX#333]
### 问题描述：
0.0.48 显示messageDialog的时候疯狂打压日志,

### 设备信息：
HUAWEI MLD-AL00 鸿蒙2.0

在一加手机 colorOs 13上没有出现,其他手机没测试

### 是否在 Demo 中能复现此问题？
未尝试

### 日志
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:131)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1626)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1529)
	at android.view.View.draw(View.java:21999)
	at androidx.constraintlayout.utils.widget.ImageFilterView.draw(ImageFilterView.java:810)
	at android.view.View.draw(View.java:21868)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:21866)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:22002)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.draw(View.java:21868)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:21866)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:22002)
	at android.view.View.draw(View.java:21868)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:21866)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:21866)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:21866)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4639)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
	at android.view.View.draw(View.java:22002)
	at com.kongzue.dialogx.style.views.BlurLinearLayout$3.onPreDraw(BlurLinearLayout.java:326)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1098)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3375)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by kongzue** [comment]
很抱歉未能在最新版本的代码中确认问题的原因，请先尝试更新至最新测试版本看看还会不会遇到此问题。
[0.0.49.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta1)

**Comment by Matcha-xiaobin** [comment]
我的是 0.0.47 ，今天给项目加上了Coil这个库，准备剔除，但还没剔除Glide相关的库，目前也出现了这个问题。

**Comment by Matcha-xiaobin** [comment]
> 很抱歉未能在最新版本的代码中确认问题的原因，请先尝试更新至最新测试版本看看还会不会遇到此问题。 [0.0.49.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta1)

我的是 0.0.47 ，今天给项目加上了Coil这个库，准备剔除，但还没剔除Glide相关的库，目前也出现了这个问题。

**Comment by kongzue** [comment]
@Matcha-xiaobin 请尝试最新的版本，针对旧版的问题已经不再处理，因为有可能在版本更新过程中已经修复。

**Comment by Matcha-xiaobin** [comment]
> @Matcha-xiaobin 请尝试最新的版本，针对旧版的问题已经不再处理，因为有可能在版本更新过程中已经修复。

经过排查问题，定位到该问题确实是Coil引起的，Coil库在默认情况下是启用了 硬件位图渲染 ，会导致大佬你的这个库出现崩溃的情况，大佬要不要看看能不能兼容一下Coil使用默认配置的情况？
以下是我目前的解决方案：
override fun newImageLoader(): ImageLoader =
        ImageLoader.Builder(this)
            .crossfade(true)
            .components {
                if (SDK_INT >= 28) {
                    add(ImageDecoderDecoder.Factory())
                } else {
                    add(GifDecoder.Factory())
                }
                add(SvgDecoder.Factory())
            }
            .allowHardware(false)//禁用 硬件位图渲染
            .logger(DebugLogger())
            .build()

**Comment by kongzue** [comment]
@Matcha-xiaobin 看来应该是硬件渲染加速的问题？（猜测）可以麻烦你尝试一下强行开启或关闭Activity硬件加速看看问题能否解决

**Comment by Matcha-xiaobin** [comment]
> @Matcha-xiaobin 看来应该是硬件渲染加速的问题？（猜测）可以麻烦你尝试一下强行开启或关闭Activity硬件加速看看问题能否解决

已尝试过，无效，依然闪退，还是那个错误

**Comment by kongzue** [comment]
@Matcha-xiaobin 如果使用IOS主题是需要使用RenderScript来完成高斯模糊的渲染，这个暂时确实没有办法完全处理。
已确认的是在最新版本中，`com.kongzue.dialogx.style.views.BlurLinearLayout.java:346` 处的 `.draw` 方法已经处于 `try{}catch{}` 中，暂时没有办法做其他处理。

**Comment by kongzue** [comment]
@Matcha-xiaobin 应该不可能，BlurLinearLayout 仅在 IOS 主题下才会生效，其他主题并不使用此组件。

**Comment by Matcha-xiaobin** [comment]
> @Matcha-xiaobin 应该不可能，BlurLinearLayout 仅在 IOS 主题下才会生效，其他主题并不使用此组件。

不是这个组件的问题，似乎是那个下沉背景那个截图，或者是显示这个截图的ImageView，我只记得好像那个控件名字有个ImageView

**Comment by kongzue** [comment]
@Matcha-xiaobin 那么你和issues提出人不是同一个问题，请仔细观察错误日志堆栈，他的问题是由 `com.kongzue.dialogx.style.views.BlurLinearLayout.java:346` 处的 `.draw` 方法引发的。

**Comment by Matcha-xiaobin** [comment]
似乎是ActivityScreenShotImageView 这个控件的，这一行 view.buildDrawingCache();


> @Matcha-xiaobin 那么你和issues提出人不是同一个问题，请仔细观察错误日志堆栈，他的问题是由 `com.kongzue.dialogx.style.views.BlurLinearLayout.java:346` 处的 `.draw` 方法引发的。

我的问题和他的，差别只在这里：
at com.kongzue.dialogx.style.views.BlurLinearLayout$3.onPreDraw(BlurLinearLayout.java:326)
他的是BlurLinearLayout，而我的是一个叫什么ImageView的，我去看了下源码里的内容，应该是ActivityScreenShotImageView
163行：view.buildDrawingCache();，引发的错误
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:131)
这里一模一样的

**Comment by kongzue** [comment]
@Matcha-xiaobin 如果可以麻烦提供一下详细的错误堆栈日志，我这边排查处理一下

**Comment by Matcha-xiaobin** [comment]
@kongzue 
FATAL EXCEPTION: main
Process: com.xiaobin.bangumi, PID: 32491
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1604)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at coil.drawable.CrossfadeDrawable.draw(CrossfadeDrawable.kt:79)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at android.view.View.draw(View.java:23194)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23197)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23197)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.buildDrawingCacheImpl(View.java:22458)
	at android.view.View.buildDrawingCache(View.java:22318)
	at android.view.View.buildDrawingCache(View.java:22270)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.drawViewImage(ActivityScreenShotImageView.java:163)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.doScreenshotActivityAndZoom(ActivityScreenShotImageView.java:118)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.refreshImage(ActivityScreenShotImageView.java:108)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.onMeasure(ActivityScreenShotImageView.java:99)
	at android.view.View.measure(View.java:26357)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3926)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2612)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2884)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by kongzue** [comment]
@Matcha-xiaobin 好的收到

**Comment by Matcha-xiaobin** [comment]
@kongzue 上面日志里看到了Coil CrossfadeDrawable相关的，我去关掉了这个，还是出现了问题，也一并贴给你看下，希望能抱到你
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1604)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at android.view.View.draw(View.java:23194)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23197)
	at android.view.View.draw(View.java:23067)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23065)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23197)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.View.buildDrawingCacheImpl(View.java:22458)
	at android.view.View.buildDrawingCache(View.java:22318)
	at android.view.View.buildDrawingCache(View.java:22270)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.drawViewImage(ActivityScreenShotImageView.java:163)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.doScreenshotActivityAndZoom(ActivityScreenShotImageView.java:118)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.refreshImage(ActivityScreenShotImageView.java:108)
	at com.kongzue.dialogx.util.views.ActivityScreenShotImageView.onMeasure(ActivityScreenShotImageView.java:99)
	at android.view.View.measure(View.java:26357)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3926)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2612)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2884)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by kongzue** [comment]
<img width="1289" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/03b24f88-d649-4b42-afb5-a31533a1f7f2">
@Matcha-xiaobin 目前看到的信息指向了 `view.buildDrawingCache()` 抛出的异常，这段代码的用途在于对主界面进行截图，以适用于下沉缩放的效果，代码使用的也是 Android View 的标准 API，如果存在问题可能需要尝试寻找是否是因为特定系统固件版本存在问题，目前尚未收到其他设备，或者已上线的 App 产品类似问题的报告，如上图所示下一个版本暂时通过 `try{}catch{}` 临时处理，但我并不能修复 Android View 底层可能存在的问题。

**Comment by Matcha-xiaobin** [comment]
> <img alt="image" width="1289" src="https://user-images.githubusercontent.com/10115359/250921194-03b24f88-d649-4b42-afb5-a31533a1f7f2.png"> @Matcha-xiaobin 目前看到的信息指向了 `view.buildDrawingCache()` 抛出的异常，这段代码的用途在于对主界面进行截图，以适用于下沉缩放的效果，代码使用的也是 Android View 的标准 API，如果存在问题可能需要尝试寻找是否是因为特定系统固件版本存在问题，目前尚未收到其他设备，或者已上线的 App 产品类似问题的报告，如上图所示下一个版本暂时通过 `try{}catch{}` 临时处理，但我并不能修复 Android View 底层可能存在的问题。

我这边设备全是安卓13的，目前我只能告诉你是因为Coil引起的，只要将Coil的allowHardware设为false就不会存在这个问题，其他原因我就不知晓了。

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/kongzue/DialogX/assets/5775066/3e9cb9c2-552d-4860-a88a-5c9e1bba233f)

**Comment by kongzue** [comment]
@Matcha-xiaobin 很抱歉我并不用Coil，所以也不清楚它是否造成了什么影响。另外我这边测试机是Android14 beta2在Google Pixel5上进行开发和调试，没有发现任何问题。且目前使用DialogX已上线的产品也并未收到类似问题的反馈。

**Comment by Matcha-xiaobin** [comment]
@kongzue 关于这个问题，我问了下AI
AI给出的答案：


当你调用view.buildDrawingCache()方法时，报错"Software rendering doesn’t support hardware bitmaps"，这通常是因为你的View正在使用硬件加速（Hardware Acceleration）而buildDrawingCache()方法在软件渲染（Software Rendering）模式下不支持硬件位图。

要解决这个问题，你可以尝试以下几种方法：

关闭硬件加速：通过在你的Activity的onCreate()方法中添加以下代码来关闭硬件加速：
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
    view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
}
这将会把该View及其子View都设置为软件渲染模式。但请注意，这可能会影响性能和绘制效果。

使用setDrawingCacheEnabled(true)代替buildDrawingCache()：在调用buildDrawingCache()之前，先设置setDrawingCacheEnabled(true)来启用缓存。然后可以直接通过getDrawingCache()方法获取缓存的位图，而不是通过buildDrawingCache()方法。
view.setDrawingCacheEnabled(true);
Bitmap bitmap = view.getDrawingCache();
使用setLayerType()方法切换硬件/软件加速：如果你不想完全关闭硬件加速，你可以尝试在调用buildDrawingCache()之前将View切换到软件渲染模式，然后再切换回硬件加速模式。
view.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
view.buildDrawingCache();
view.setLayerType(View.LAYER_TYPE_HARDWARE, null);
这将只在执行buildDrawingCache()时将View切换到软件渲染模式，然后再切换回硬件加速模式。

也许可以尝试下，

等我有时间了，我也可以下载源码依赖到项目，尝试下这些方案

**Comment by sceneren** [comment]
应该也是界面使用了coil 加载图片的问题

**Comment by kongzue** [comment]
请更新至最新版本 https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta3
