### ISSUE TITLE
BottomDialog和WaitDialog 先后弹出，程序闪退。app窗口化发现只有dialogfragment模式可以正常显示弹窗

### ISSUE THREAD

**Issue by Li4526330** [kongzue/DialogX#336]
at com.kongzue.dialogx.impl.DialogFragmentImpl$1.onTouch(DialogFragmentImpl.java:81)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:14845)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3312)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2973)
                                                                                                    	at com.kongzue.dialogx.impl.DialogFragmentImpl$1.onTouch(DialogFragmentImpl.java:81)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:14845)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3312)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2973)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2930)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2930)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3326)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2930)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:846)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:2065)
                                                                                                    	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1432)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:771)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15112)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7915)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7649)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7043)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7100)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7066)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7248)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7074)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7305)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7047)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7100)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7066)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7074)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7047)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10482)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10384)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10337)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10729)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:310)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:374)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:163)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9596)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
2023-07-03 17:09:50.916 31312-31312 AndroidRuntime          pid-31312                            E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by kongzue** [comment]
问题重复：https://github.com/kongzue/DialogX/issues/336 已在 https://github.com/kongzue/DialogX/commit/b27867ff7ae34e91b46f8ce0099b97c28eda598f 解决。
