### ISSUE TITLE
【BUG反馈】请填写标题

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogX#341]
## BUG 反馈
#333 和这个是一样的

### 问题描述：
闪退

************* Crash Head ****************
Time Of Crash      : 2023_07_21-14_08_40
Rom Info           : RomInfo{name=oneplus, version=ne2210_13.1.0.181(cn01)}
Device Manufacturer: OnePlus
Device Model       : NE2210
Android Version    : 13
Android SDK        : 33
App VersionName    : 1.0
App VersionCode    : 1
************* Crash Head ****************

android.renderscript.RSInvalidStateException: Calling RS with no Context active.
	at android.renderscript.RenderScript.validate(RenderScript.java:1246)
	at android.renderscript.RenderScript.destroy(RenderScript.java:1660)
	at com.kongzue.dialogx.style.views.BlurLinearLayout.releaseScript(BlurLinearLayout.java:201)
	at com.kongzue.dialogx.style.views.BlurLinearLayout.release(BlurLinearLayout.java:212)
	at com.kongzue.dialogx.style.views.BlurLinearLayout.destroy(BlurLinearLayout.java:406)
	at com.kongzue.dialogx.style.views.BlurLinearLayout.onDetachedFromWindow(BlurLinearLayout.java:398)
	at android.view.View.dispatchDetachedFromWindow(View.java:21565)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4021)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4011)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5667)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5638)
	at android.view.ViewGroup.removeView(ViewGroup.java:5569)
	at com.kongzue.dialogx.interfaces.BaseDialog$6.run(BaseDialog.java:423)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8416)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by kongzue** [comment]
请更新至 [0.0.49.beta4](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta4)
