### ISSUE TITLE
【BUG反馈】NullPointerException 空指针

### ISSUE THREAD

**Issue by wangkai9799** [kongzue/DialogX#342]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
偶现的崩溃

同https://github.com/kongzue/DialogX/issues/274

使用的DialogX版本为0.0.48

Logcat日志：
```
Process Name: 'com.youdao.square'
Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: {CanCatch}{main} Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference
	at com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:225)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6747)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Back traces ends.
```

### 设备信息：
华为：POT-AL10   Android版本：Android10 鸿蒙

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
无

**Comment by kongzue** [comment]
请更新至最新版本

**Comment by wangkai9799** [comment]
使用的已经是最新版本：0.0.48

**Comment by wangkai9799** [comment]
<img width="1024" alt="image" src="https://github.com/kongzue/DialogX/assets/34116538/acb0a8cf-650b-4995-a4e2-e304631c3bb2">
好像是这个方法为空了

**Comment by kongzue** [comment]
请确认使用最新版本[0.0.49.beta4](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta4)
