### ISSUE TITLE
【BUG反馈】100% ERROR：  no event down from INITIALIZED

### ISSUE THREAD

**Issue by k3sc** [kongzue/DialogX#345]
### 问题描述：
` java.lang.IllegalStateException: no event down from INITIALIZED
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:142)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
                                                                                                    	at com.kongzue.dialogx.interfaces.DialogLifecycleCallback.onDismiss(DialogLifecycleCallback.java:27)
                                                                                                    	at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$1.onDismiss(WaitDialog.java:365)
                                                                                                    	at com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.onDetachedFromWindow(DialogXBaseRelativeLayout.java:175)
                                                                                                    	at android.view.View.dispatchDetachedFromWindow(View.java:20534)
                                                                                                    	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3942)
                                                                                                    	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5560)
                                                                                                    	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5531)
                                                                                                    	at android.view.ViewGroup.removeView(ViewGroup.java:5462)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog$7.run(BaseDialog.java:257)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

### 设备信息：
Android 11

使用了SerialPortHelper，在setISerialPortDataListener的onDataReceived里，调用了
`TipDialog.show("Success!", WaitDialog.TYPE.SUCCESS, 3500);`
show的时候没有报错onDismiss的时候报错了

**Comment by k3sc** [comment]
0.0.43.beta12 > 0.0.48   It's already resolved
