### ISSUE TITLE
【BUG反馈】 PopTip.show存在问题

### ISSUE THREAD

**Issue by lbwengineer** [kongzue/DialogX#352]
### 问题描述

new Thread(()->{
            for (int i = 0; i < 10000; i++) {
                PopTip.show("邮件已发送"+i, "撤回").autoDismiss(200);
                Thread.sleep(100);
            }
        }).start();
执行上面的代码时意外崩溃了，执行了比较多次数后必定崩溃。

### 设备信息

雷电模拟器9.0.29

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

### 错误日志

```java
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.kongzue.dialogx.dialogs.PopTip.waitForDismiss(PopTip.java:781)
	at com.kongzue.dialogx.dialogs.PopTip.access$2400(PopTip.java:54)
	at com.kongzue.dialogx.dialogs.PopTip$DialogImpl$8$1.run(PopTip.java:697)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

**Comment by kongzue** [comment]
请确认已更新到最新版本再试：https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta9
