### ISSUE TITLE
【BUG反馈】 FullScreenDialog onbindview传入的布局id，然后在onBind里使用databinding绑定布局，0.0.47版本没问题，0.0.49 beta12闪退

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#361]
### 问题描述

FullScreenDialog onbindview传入的布局id，然后在onBind里使用databinding绑定布局，0.0.47版本没问题，0.0.49 beta12闪退
![image](https://github.com/kongzue/DialogX/assets/5775066/25081a07-2490-4175-bee3-526a245e9774)
java.lang.IllegalArgumentException: View is not a binding layout
at com.kongzue.dialogx.interfaces.OnBindView.bindParent(OnBindView.java:180)
at com.kongzue.dialogx.dialogs.FullScreenDialog$DialogImpl.refreshView(FullScreenDialog.java:321)
at com.kongzue.dialogx.dialogs.FullScreenDialog$DialogImpl.<init>(FullScreenDialog.java:162)
at com.kongzue.dialogx.dialogs.FullScreenDialog.show(FullScreenDialog.java:115)
看起来似乎是回调里给的view不是我传入的layoutId生成的那个布局，而是改成了parentView了，我觉得还是需要返回自定义的布局的。方便使用databinding或viewbinding绑定布局。

### DialogX 版本

0.0.49 beta12

### 设备信息

魅族20pro，android 13

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
很抱歉我这边没办法解决databinding存在的问题。

**Comment by Matcha-xiaobin** [comment]
> 

demo中那个 底部列表recyclerview 那个点击会闪退，似乎也是因为改了这个返回的view导致崩了

**Comment by com13117340768** [comment]
使用ViewBinding
