### ISSUE TITLE
【BUG反馈】 偶现崩溃

### ISSUE THREAD

**Issue by Sunxyao** [kongzue/DialogX#378]
### 问题描述

冷起时首次启动dialog

### DialogX 版本

0.0.49.beta4

### 设备信息

华为 mate40

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

### 错误日志

```java
java.lang.NullPointerException: Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference in method 'void com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run()'
        at com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:227)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8240)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by kongzue** [comment]
尝试更新到最新测试版本看看

**Comment by Sunxyao** [comment]
> 尝试更新到最新测试版本看看

辛苦回复，使用0.0.49.beta18 版本目前测试还没有复现过，待后续验证
