### ISSUE TITLE
【BUG反馈】 神奇的闪退

### ISSUE THREAD

**Issue by PoisonGZ** [kongzue/DialogX#400]
### 问题描述

项目使用了Proguard混淆（DialogX混淆规则已正确添加），dex控制流混淆和dialogX，任意两个都可以使用，但是三个同时使用就会闪退

### DialogX 版本

0.0.48->0.0.49.beta22

### 设备信息

Mi 10 Pro

### 是否在 Demo 中能复现此问题？

否

### 错误日志

```java
Crash type: 'java'
Start time: '2023-11-11T23:31:53.366+0800'
Crash time: '2023-11-11T23:31:53.806+0800'
App ID: 'com.test.demo'
App version: '1.0'
Rooted: 'No'
API level: '34'
OS version: '14'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'Xiaomi'
Brand: 'Xiaomi'
Model: 'Mi 10 Pro'
Build fingerprint: 'Xiaomi/cmi/cmi:14/UKQ1.230804.001/V816.0.18.0.UNBCNXM:user/release-keys'
pid: 24710, tid: 24710, name: main  >>> com.hades.proton <<<

java stacktrace:
java.lang.InstantiationError: com.kongzue.dialogx.interfaces.OnBindView
	at com.test.demo.MainActivity.onCreate(Unknown Source:613)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3954)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4125)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2573)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8686)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by PoisonGZ** [comment]
我已经发现问题，已修复，谢谢

**Comment by PoisonGZ** [comment]
我已经找到原因，目前已修复

**Comment by PoisonGZ** [comment]
谢谢
