### ISSUE TITLE
【BUG反馈】 Crash WaitDialog in API 23

### ISSUE THREAD

**Issue by AlirezaIvaz** [kongzue/DialogX#419]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

WaitDialog and TIpDialog crash when dismiss on Android 6 emulator. I've tested demo app and same crash happened. Of course it works properly in my Android 13 phone.

### DialogX 版本

0.0.50.beta7

### 设备信息

Pixel XL API 23 (Android 6 emulator)

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

### 错误日志

```java
2024-01-28 22:05:23.528 18065-18065 >>>                     com.kongzue.dialogxdemo              I  WaitDialog(895ae46).show on com.kongzue.dialogxdemo.activity.MainActivity@80afa30
2024-01-28 22:05:23.545 18065-18092 AndroidRuntime          com.kongzue.dialogxdemo              E  FATAL EXCEPTION: Thread-719
                                                                                                    Process: com.kongzue.dialogxdemo, PID: 18065
                                                                                                    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                                                    	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6556)
                                                                                                    	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:942)
                                                                                                    	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5081)
                                                                                                    	at android.view.View.invalidateInternal(View.java:12713)
                                                                                                    	at android.view.View.invalidate(View.java:12677)
                                                                                                    	at android.view.View.invalidate(View.java:12661)
                                                                                                    	at com.kongzue.dialogx.util.views.ProgressView$1.onValueUpdate(ProgressView.java:118)
                                                                                                    	at com.kongzue.dialogx.util.DialogXValueAnimator$1.run(DialogXValueAnimator.java:71)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)
2024-01-28 22:05:28.289 18065-18065 >>>                     com.kongzue.dialogxdemo              I  WaitDialog(895ae46).dismiss
```
```

**Comment by kongzue** [comment]
This will be fixed in the next beta

**Comment by kongzue** [comment]
Version [0.0.50.beta8](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta8)  has been updated.
