### ISSUE TITLE
【BUG反馈】 使用 MessageDialog 唤起 FullScreenDialog 时出现 BUG。

### ISSUE THREAD

**Issue by HChenX** [kongzue/DialogX#423]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

- 使用 MessageDialog 唤起 FullScreenDialog 时 MessageDialog 的圆角消失，且 FullScreenDialog 也没有圆角（我也不知道为什么，使用Demo打开FullScreenDialog是有圆角的，自己写就没了）。
- 当FullScreenDialog关闭时，会发现MessageDialog并没有在唤醒Full时关闭，很突兀。
- 而且当我更新最新0.0.50.beta9版本时，向下滑动关闭Full会崩溃。
- 下面是日志：
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 31926
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.hchen.foregroundpin
[Version Name]: 1.3
[Version Code]: 2024012600
[Target SDK]: 34
[Min SDK]: 30
[Error Type]: JVM
[Crash Time]: 2024-02-28T12:47:00.834
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.kongzue.dialogx.interfaces.ScrollController.lockScroll(boolean)' on a null object reference
	at com.kongzue.dialogx.util.FullScreenDialogTouchEventInterceptor$1.onTouch(FullScreenDialogTouchEventInterceptor.java:111)
	at android.view.View.dispatchTouchEvent(View.java:15099)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3178)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2820)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at com.kongzue.dialogx.util.views.MaxRelativeLayout.dispatchTouchEvent(MaxRelativeLayout.java:258)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3206)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4409)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15387)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7110)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6869)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6284)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6341)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6307)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6472)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6315)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6529)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6288)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6341)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6307)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6315)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6288)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9549)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9500)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9455)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9694)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:291)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

- 下面是我的代码示例：
![image](https://github.com/kongzue/DialogX/assets/123531821/c96514fc-86ff-4842-a92f-c095b63f0fce)

![image](https://github.com/kongzue/DialogX/assets/123531821/f016458c-4ef7-40c9-b836-03c3c28bfd67)

- 下面是视频演示：

https://github.com/kongzue/DialogX/assets/123531821/8b06f893-673a-4aac-9962-8b52c5e2360d

https://github.com/kongzue/DialogX/assets/123531821/d7780820-47b6-491a-9f96-ed35d7e7507d

- 如果需要其他信息可以随时叫我。

### DialogX 版本

0.0.50.beta9

### 设备信息

Redmi K50

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
此问题会在下一个测试版修复

**Comment by kongzue** [comment]
关于圆角消失的问题是因为 DialogX 的圆角是由OutlineProvider实现的，而要实现 FullScreenDialog 的背景下沉效果，需要对当前屏幕进行截图后执行动画实现，但是无法对OutlineProvider实现的圆角截图，因此圆角会消失，同样的MessageDialog没有在启动FullScreenDialog时消失也是同理，因为截图的瞬间MessageDialog并没有关闭，要解决此问题的简单方案是直接关掉FullScreenDialog的背景下沉效果：
```java
.setHideZoomBackground(true)
```
关于闪退的问题已经在最新的 beta版本修复：[0.0.50.beta10测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta10)

**Comment by HChenX** [comment]
> 关于圆角消失的问题是因为 DialogX 的圆角是由OutlineProvider实现的，而要实现 FullScreenDialog 的背景下沉效果，需要对当前屏幕进行截图后执行动画实现，但是无法对OutlineProvider实现的圆角截图，因此圆角会消失，同样的MessageDialog没有在启动FullScreenDialog时消失也是同理，因为截图的瞬间MessageDialog并没有关闭，要解决此问题的简单方案是直接关掉FullScreenDialog的背景下沉效果：
> 
> ```java
> .setHideZoomBackground(true)
> ```
> 
> 关于闪退的问题已经在最新的 beta版本修复：[0.0.50.beta10测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta10)

好的，感谢
