### ISSUE TITLE
【BUG反馈】 NullPointerException

### ISSUE THREAD

**Issue by YoungNatty** [kongzue/DialogX#465]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

BottomMenu深色模式下100%空指针（DialogXMaterialYou）

### DialogX 版本

0.0.50.beta17.1

### 设备信息

SonySO-51B

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

截屏/视频

### 错误日志

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.TextView.getVisibility()' on a null object reference
```

**Comment by kongzue** [comment]
此问题系已知问题，会在下一个版本修复，相关修复代码已提交，等待合并更新版本

**Comment by YoungNatty** [comment]
0.0.50.beta18修复了吗？

**Comment by kongzue** [comment]
复测没有发现问题，如还是有遇到问题劳烦提交一下具体的错误堆栈，根据您提交的信息无法确认具体原因

**Comment by YoungNatty** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.TextView.getVisibility()' on a null object reference
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog$DialogImpl.refreshView(BottomDialog.java:543)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog$1.run(BottomDialog.java:803)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog.runOnMain(BaseDialog.java:747)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog.refreshUI(BottomDialog.java:800)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomMenu.refreshUI(BottomMenu.java:659)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomMenu.onDialogShow(BottomMenu.java:613)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog.access$700(BottomDialog.java:61)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog$DialogImpl$1.onShow(BottomDialog.java:370)
                                                                                                    	at com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.onAttachedToWindow(DialogXBaseRelativeLayout.java:258)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:21305)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
                                                                                                    	at android.view.ViewGroup.addViewInner(ViewGroup.java:5291)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5077)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5017)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:4989)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog$3.run(BaseDialog.java:258)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog.runOnMain(BaseDialog.java:747)
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog.show(BaseDialog.java:248)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomDialog.show(BottomDialog.java:224)
                                                                                                    	at com.kongzue.dialogx.dialogs.BottomMenu.show(BottomMenu.java:138)

**Comment by kongzue** [comment]
请确认您是[最新的beta版本](https://github.com/kongzue/DialogX/releases)，相关代码已经在之前的测试版本中修复并提交合并了，针对已经处理的问题不再进行处理。
<img width="967" alt="image" src="https://github.com/user-attachments/assets/d16fe7c6-2742-405c-b4b3-84bf5e1d757b">

**Comment by kongzue** [comment]
劳烦更新到 [0.0.50.beta19](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta19) 测试一下应该没问题了

**Comment by YoungNatty** [comment]
ok，修复了，麻烦啦
