### ISSUE TITLE
DialogX有时候会报Attempt to invoke virtual method 'boolean com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.post(java.lang.Runnable)' on a null object reference

### ISSUE THREAD

**Issue by 18691886351** [kongzue/DialogX#66]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.post(java.lang.Runnable)' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.doDismiss(WaitDialog.java:471)
        at com.kongzue.dialogx.dialogs.WaitDialog.doDismiss(WaitDialog.java:574)
        at com.kongzue.dialogx.dialogs.WaitDialog.dismiss(WaitDialog.java:578)
        at com.example.students_demo.MyApplication$MyReceiver.onReceive(MyApplication.java:50)

**Comment by kongzue** [comment]
请更新至最新测试版：
![image](https://user-images.githubusercontent.com/10115359/124060316-5f446c00-da5f-11eb-879f-2f43ca20cb4e.png)
此问题在beta6得到修复，但我依然推荐更新至beta8获得更稳定的体验。
