### ISSUE TITLE
WaitDialog崩溃

### ISSUE THREAD

**Issue by Orienser** [kongzue/DialogX#74]
**版本：**
0.0.40.beta11

**重新步骤：**
`WaitDialog.setMessage("Hello").show();`

**堆栈日志：**
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kongzue.dialogx.util.views.BlurView.setOverlayColor(int)' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.refreshView(WaitDialog.java:439)
        at com.kongzue.dialogx.dialogs.WaitDialog$3.run(WaitDialog.java:582)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:239)
        at android.app.ActivityThread.main(ActivityThread.java:8209)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

**可能原因分析：**
1. 先调用的setMessage()会执行refreshUI()：
```java
runOnMain(()->{
    if (dialogImpl != null)
        dialogImpl.refreshView();    // 一：异步执行
});
```
2. 后调用的show()包含下面一段代码：
```java
dialogImpl = new DialogImpl(layoutResId);    // 二：同步执行
runOnMain(()->{
    dialogImpl.lazyCreate();    // 三：异步执行
    ...
});
```
3. 执行顺序为：二 > 一 > 三；执行到一时，refreshView()中的blurView==null，抛出NPE。

**Comment by kongzue** [comment]
请直接使用：
```
WaitDialog.show("Hello");
```
此问题也会在下一个版本解决。

**Comment by kongzue** [comment]
请尝试最新的测试版本：0.0.40.beta13
