### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by gazerhuang** [kongzue/DialogX#78]
`java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$4.run(WaitDialog.java:452)`
版本：0.0.39~0.0.40.beta11
收集上来的日志，不清楚如何触发的，请教一下这种错误可能在什么情况下会出现，该如何避免？谢谢

**Comment by kongzue** [comment]
请测试下最新的beta13，我这边已经检查了所有的代码，WaitDialog目前没有单独调用getContext().getResources()指令的地方了。

因为 DialogX 是在初始化init后自动获取当前界面Activity句柄的（getContext()）然而这个过程可能出现因为界面生命周期步调不一致或因为对话框组件需要post到主线程执行产生了延迟的问题致使在显示时获取到实际Activity对象为空，此问题将继续关注并进行处理。

**Comment by gazerhuang** [comment]
> 请测试下最新的beta13

我更新了beta13，还是有这个报错

**Comment by kongzue** [comment]
很抱歉我暂时无法找到原因，如果可以请给出具体的错误日志堆栈信息，我这边目前找不到会引发空指针的问题所在。

**Comment by gazerhuang** [comment]
``` 
07-16 16:39:00.767 8625 8625 D CrashReport: >>> com.xxx.xxx.XActivity onResumed <<<

15007-16 16:39:00.807 8625 8625 I >>> : WaitDialog(35b64f9).show
15807-16 16:39:04.446 8625 8625 D CrashReport: >>> com.xxx.xxx.XActivity onPaused <<<
16707-16 16:39:11.524 8625 23344 D XActivity: onResponse: File/202107/16/gd20210705114420163901.png
17007-16 16:39:12.827 8625 8625 I Timeline: Timeline: Activity_launch_request time:3736322
17107-16 16:39:12.837 8625 8625 D CrashReport: >>> com.xxx.xxx.XActivity onDestroyed <<<
17207-16 16:39:12.895 8625 8625 D AndroidRuntime: Shutting down VM
173--------- beginning of crash
17407-16 16:39:12.895 8625 8625 E AndroidRuntime: FATAL EXCEPTION: main
17507-16 16:39:12.895 8625 8625 E AndroidRuntime: Process: com.xxx.xxx, PID: 8625
17607-16 16:39:12.895 8625 8625 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
17707-16 16:39:12.895 8625 8625 E AndroidRuntime: at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:138)
17807-16 16:39:12.895 8625 8625 E AndroidRuntime: at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$4.run(WaitDialog.java:480)
17907-16 16:39:12.895 8625 8625 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
18007-16 16:39:12.895 8625 8625 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
18107-16 16:39:12.895 8625 8625 E AndroidRuntime: at android.os.Looper.loop(Looper.java:233)
18207-16 16:39:12.895 8625 8625 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7892)
18307-16 16:39:12.895 8625 8625 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
18407-16 16:39:12.895 8625 8625 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
18507-16 16:39:12.895 8625 8625 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
18607-16 16:39:12.901 8625 8625 E CrashReport: Java Crash Happen cause by main(2)
```
业务逻辑是：拍照→显示WaitDialog→上传→成功或失败显示TipDialog

**Comment by kongzue** [comment]
麻烦问下您是否有完成DialogX的初始化操作呢？初始化方法详见 wiki。

**Comment by gazerhuang** [comment]
> 麻烦问下您是否有完成DialogX的初始化操作呢？初始化方法详见 wiki。

有的，在application中初始化的

**Comment by kongzue** [comment]
但是根据日志推断，这里去获取context时出现了空指针的问题。而DialogX在[BaseDialog.getContext()](https://github.com/kongzue/DialogX/blob/22972a726cf1f38a53ecc9aae0562fee5195c137/DialogX/src/main/java/com/kongzue/dialogx/interfaces/BaseDialog.java#L211)时是会检查的，若context为空还会尝试强行通过反射获取当前正在运行的Activity，如果这也无法生效，就不清楚为何了。

**Comment by gazerhuang** [comment]
这个错误测试复现不了，应该在极端情况下才会发生，我之后再多看几个日志找找原因，感谢您的解答。
